# Generated by Django 4.2.9 on 2024-02-17 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_feeds', '0003_adpost_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='object_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
